spring:
  application:
    name: product
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
env: dev5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
girl:
  name: lala
  age: 21
management:
  endpoints:
    web:
      exposure:
        include: "*"
