spring:
  application:
    name: product
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
    bus:
      refresh:
        enabled: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
env: dev5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
girl:
  name: lala
  age: 23
