spring:
  application:
    name: product
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
env: dev2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
